# Generated by Django 3.1.1 on 2020-11-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successful_order',
            name='ordered_link',
            field=models.IntegerField(default=1),
        ),
    ]
