# Generated by Django 3.1.1 on 2020-11-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201109_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successful_order',
            name='ordered_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_order_id', to='main_app.order'),
        ),
    ]
