# Generated by Django 3.1.1 on 2020-11-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201109_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='item_link',
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_name',
            field=models.CharField(default='item', max_length=10),
        ),
    ]
