# Generated by Django 3.1.1 on 2020-11-09 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201110_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='item_name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='main_app.item'),
        ),
    ]
